//mutation 常量统一配置
export default {
  CATCH_IMG: 'CATCH_IMG',
  CHANGE_PRODUCT: 'CHANGE_PRODUCT',
  CHANGE_OPENID: 'CHANGE_OPENID',
  CHANGE_ONLINE: 'CHANGE_ONLINE',
  CHANGE_MEDIA_ID: 'CHANGE_MEDIA_ID',
  CHANGE_BASIC_INFO: 'CHANGE_BASIC_INFO',
  CHANGE_DEVICE_STATE: 'CHANGE_DEVICE_STATE',
  CHANGE_STATE_LED: 'CHANGE_STATE_LED',
  CHANGE_STATE_BAT: 'CHANGE_STATE_BAT',
  CHANGE_STATE_OTA: 'CHANGE_STATE_OTA',
  CHANGE_STATE_CHILDLOCK: 'CHANGE_STATE_CHILDLOCK',
  CHANGE_STATE_WECHAT: 'CHANGE_STATE_WECHAT',
  CHANGE_STATE_POWER: 'CHANGE_STATE_POWER',
  CHANGE_STATE_SLEEP: 'CHANGE_STATE_SLEEP',
  CHANGE_STATE_PLAYER: 'CHANGE_STATE_PLAYER',
  CHANGE_STATE_REST_SLEEP: 'CHANGE_STATE_REST_SLEEP',
  CHANGE_STATE_SONGS: 'CHANGE_STATE_SONGS',
  CHANGE_LISTEN_ITEM: 'CHANGE_LISTEN_ITEM',
  CHANGE_LISTENING_ITEM: 'CHANGE_LISTENING_ITEM',
  CHANGE_PLAY_URL: 'CHANGE_PLAY_URL',
  CHANGE_SHOW_PROPELLING: 'CHANGE_SHOW_PROPELLING',
  CHANGE_SEND_ITEM: 'CHANGE_SEND_ITEM', // 推送的歌曲
  CHNAGE_PLAY_LIST: 'CHNAGE_PLAY_LIST', //播放专辑列表


  CHANGE_PLAY_MODE: 'CHANGE_PLAY_MODE', //播放模式  单曲 循环 顺序

  CHANGE_STATE_POWER: 'CHANGE_STATE_POWER',

  CHANGE_STATE_VERSION: 'CHANGE_STATE_VERSION',

  CHANGE_STATE_OTA: 'CHANGE_STATE_OTA',

  CHANGE_STATE_REST_SLEEP: 'CHANGE_STATE_REST_SLEEP',

  CHANGE_STATE_SLEEP: 'CHANGE_STATE_SLEEP',

  CHANGE_STATE_PLAYER_PROGRESS: 'CHANGE_STATE_PLAYER_PROGRESS',

  CHANGE_STATE_STORAGE: 'CHANGE_STATE_STORAGE',

  CHANGE_STATE_VOL: 'CHANGE_STATE_VOL',
}
/* ================================================================ */
export const CHANGE_OPENID = "CHANGE_OPENID" // 更改openid
export const CHANGE_DEVICE_ID = "CHANGE_DEVICE_ID" // 更改device_id

export const CHANGE_VOLUME = "CHANGE_VOLUME" // 更改volume

export const CHANGE_LIGHT_STATUS = "CHANGE_LIGHT_STATUS" // 更改台灯的开关状态
export const CHANGE_LIGHTNESS = "CHANGE_LIGHTNESS" // 更改台灯的亮度
export const CHANGE_MODE = "CHANGE_MODE" // 更改台灯的的模式
export const CHANGE_RA = "CHANGE_RA" // 更改台灯的指数值
export const CHANGE_UPDATING_PLAN = "CHANGE_UPDATING_PLAN" // 更改台灯的指数值

export const CHANGE_LED_ON_TIME = "CHANGE_LED_ON_TIME" // 更改台灯的使用时间
export const CHANGE_SIT_NORMAL_TIME = "CHANGE_SIT_NORMAL_TIME" // 更改坐姿正常时间
export const CHANGE_SIT_ERROR_TIME = "CHANGE_SIT_ERROR_TIME" // 更改坐姿错误时间
export const CHANGE_SIT_REMIND_COUNT = "CHANGE_SIT_REMIND_COUNT" // 更改坐姿提醒次数
export const CHANGE_REST_REMIND_COUNT = "CHANGE_REST_REMIND_COUNT" // 更改休息提醒次数

export const CHANGE_PLAYING_SONG = "CHANGE_PLAYING_SONG" // 更改休息提醒次数
